<?php

namespace Alastyn\AdminBundle\Repository;

/**
 * AppellationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppellationRepository extends \Doctrine\ORM\EntityRepository
{
}
