alastyn_front:
    resource: "@AlastynFrontBundle/Controller/"
    type:     annotation
    prefix:   /

alastyn_user:
    resource: "@AlastynUserBundle/Controller/"
    type:     annotation
    prefix:   /

alastyn_admin:
    resource: "@AlastynAdminBundle/Controller/"
    type:     annotation
    prefix:   /

test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:  /admin/login
    defaults: { _controller: AlastynUserBundle:Security:login }

login_check:
    path: /admin/login_check

logout:
    path: /admin/logout
    defaults: { _controller: AlastynUserBundle:Security:logout }
