services:
    check_rss:
         class: Alastyn\AdminBundle\Services\CheckRSS

    check_datas:
         class: Alastyn\AdminBundle\Services\CheckDatas

    check_datas:
	    class: Alastyn\AdminBundle\Services\CheckRSSFeedValidator