services:
#    alastyn_admin.example:
#        class: Alastyn\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

 gbprod.my_service:
     class: Alastyn\AdminBundle\Resources\config